# Generated by Django 3.1.7 on 2021-03-28 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField(unique=True)),
                ('start_call', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 23, 14, 7, 946482))),
                ('end_call', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=13, null=True)),
                ('destination', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'unique_together': {('call_id', 'source')},
            },
        ),
    ]
