# Generated by Django 3.1.7 on 2021-03-29 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='start_call',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 18, 19, 7, 188020)),
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('start_call', 'end_call')},
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='call_id',
        ),
    ]
